# Generated by Django 5.0.6 on 2024-07-12 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_role_delete_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='role',
            new_name='name',
        ),
    ]
