# Generated by Django 5.0.7 on 2024-07-19 06:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_librarianloginhistory_librarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarianloginhistory',
            name='librarian',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.librarian'),
        ),
    ]
