# Generated by Django 4.2 on 2024-06-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0002_loginhistory'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='loginhistory',
            table='librarians_login_histories',
        ),
    ]
