# Generated by Django 5.0.6 on 2024-07-10 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0004_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('96d31e5e-a0f3-46a0-acbc-9c2d5376e4dc')),
        ),
    ]
