# Generated by Django 5.0.6 on 2024-07-10 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0005_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('43cbe37c-ca84-4e71-bc98-2bd215fd0e8b')),
        ),
    ]
