# Generated by Django 5.0.6 on 2024-07-10 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0006_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a55a91a5-93c4-496e-bf36-c672850c59b6')),
        ),
    ]
