# Generated by Django 5.0.6 on 2024-07-10 10:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0007_alter_librarians_email_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('2fcb5fbd-6516-4aa1-8115-78c5ae78343c')),
        ),
    ]
