# Generated by Django 5.0.6 on 2024-07-12 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0008_alter_librarians_email_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ccb160bd-804f-4527-bcbd-333de301dfc2')),
        ),
    ]
