# Generated by Django 5.0.6 on 2024-07-12 03:10

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0010_remove_librarians_email_remove_librarians_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarians',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='librarians',
            name='user',
        ),
        migrations.AddField(
            model_name='librarians',
            name='email',
            field=models.EmailField(default=datetime.datetime(2024, 7, 12, 3, 9, 56, 642818, tzinfo=datetime.timezone.utc), max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarians',
            name='name',
            field=models.CharField(default=datetime.datetime(2024, 7, 12, 3, 10, 0, 628769, tzinfo=datetime.timezone.utc), max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarians',
            name='password',
            field=models.CharField(default=datetime.datetime(2024, 7, 12, 3, 10, 3, 855783, tzinfo=datetime.timezone.utc), max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('54ab208e-edb8-459a-8bb6-3aa3bc7b5a3c')),
        ),
    ]
