# Generated by Django 5.0.6 on 2024-07-12 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0011_remove_librarians_picture_remove_librarians_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6ef57b61-22f2-4a91-ade4-2b1b19a10cf9')),
        ),
    ]
