# Generated by Django 5.0.6 on 2024-07-12 03:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0012_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ff71097d-c72c-4989-9905-fa63f177b313')),
        ),
    ]
