# Generated by Django 5.0.6 on 2024-07-12 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0013_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e9657dfd-1678-4fc2-8492-0ceebf8f5642')),
        ),
    ]
