# Generated by Django 5.0.6 on 2024-07-12 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0014_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('856f10d7-725c-46fc-91bc-fa4ae15171f7')),
        ),
    ]
