# Generated by Django 5.0.6 on 2024-07-12 03:51

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0015_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('0d98bb0f-7a0c-4bd5-af24-c8c24cc3a0f2')),
        ),
    ]
