# Generated by Django 5.0.6 on 2024-07-12 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0016_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6fed0670-22bc-4ae9-9cd5-d1e1f37aa012')),
        ),
    ]
