# Generated by Django 5.0.6 on 2024-07-12 04:07

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('librarians', '0017_alter_librarians_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='librarians',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('e8bae497-c18d-4c63-bd04-317ee34edab7')),
        ),
    ]
