# Generated by Django 4.2 on 2024-07-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='stock',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
