# Generated by Django 5.0.6 on 2024-07-10 07:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_alter_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='published_year',
            field=models.PositiveIntegerField(blank=True, help_text='Use the following format: <YYYY>', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2024)]),
        ),
    ]
