# Generated by Django 5.0.7 on 2024-07-14 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_book_created_at_book_updated_at_category_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='xxxxxxxxx-x', max_length=15),
        ),
    ]
