# Generated by Django 5.0.7 on 2024-07-14 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0004_book_isbn"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="category",
        ),
        migrations.AddField(
            model_name="book",
            name="category",
            field=models.ManyToManyField(to="book.category"),
        ),
    ]
