# Generated by Django 4.2 on 2024-06-26 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('members', '0001_initial'),
        ('books', '0001_initial'),
        ('librarians', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookLoans',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, null=True)),
                ('loan_date', models.DateTimeField()),
                ('due_date', models.DateTimeField()),
                ('return_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.book')),
                ('issued_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='librarians.librarians')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='members.members')),
            ],
            options={
                'db_table': 'book_loans',
            },
        ),
    ]
