# Generated by Django 4.2 on 2024-06-26 07:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
        ('books', '0001_initial'),
        ('book_loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='members.members'),
        ),
    ]
