# Generated by Django 4.2 on 2024-07-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_loans', '0003_rename_issued_by_bookloans_librarians'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='return_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
