# Generated by Django 5.0.6 on 2024-07-05 02:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_loans', '0004_alter_bookloans_return_date'),
        ('books', '0002_book_stock'),
        ('librarians', '0003_alter_loginhistory_table'),
        ('members', '0006_alter_members_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloans',
            name='book',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.book'),
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='librarians',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='librarians.librarians'),
        ),
        migrations.AlterField(
            model_name='bookloans',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='members.members'),
        ),
    ]
