# Generated by Django 5.0.6 on 2024-07-09 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_loans', '0005_alter_bookloans_book_alter_bookloans_librarians_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookloans',
            old_name='librarians',
            new_name='librarian',
        ),
    ]
