# Generated by Django 5.0.7 on 2024-07-16 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='loan_date',
            field=models.DateTimeField(),
        ),
    ]
