# Generated by Django 5.0.7 on 2024-07-16 05:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_alter_bookloan_loan_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookloan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 7, 16, 5, 53, 54, 878346, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bookloan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
