# Generated by Django 5.0.7 on 2024-07-17 03:48

import loans.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loans", "0005_alter_bookloan_loan_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookloan",
            name="due_date",
            field=models.DateTimeField(),
        ),
    ]
