# Generated by Django 5.0.7 on 2024-07-17 04:05

import loans.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_bookloan_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookloan',
            name='loan_date',
            field=models.DateTimeField(validators=[loans.validators.validate_loan_date]),
        ),
    ]
