# Generated by Django 4.2 on 2024-07-03 05:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='uniq_code',
            field=models.UUIDField(default=uuid.UUID('7159cb38-38d8-4a14-b38d-aa99818f5dc3'), editable=False),
        ),
    ]
