# Generated by Django 4.2 on 2024-07-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_members_uniq_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='uniq_code',
        ),
        migrations.AddField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='93080345', editable=False, max_length=8),
        ),
    ]
