# Generated by Django 4.2 on 2024-07-03 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_remove_members_uniq_code_members_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='025950513486265', editable=False, max_length=15),
        ),
    ]
