# Generated by Django 5.0.6 on 2024-07-04 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_alter_members_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='919767233748919', editable=False, max_length=15),
        ),
    ]
