# Generated by Django 5.0.6 on 2024-07-05 02:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_alter_members_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='810779514016329', editable=False, max_length=15),
        ),
    ]
