# Generated by Django 5.0.6 on 2024-07-10 10:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0020_alter_members_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('1aab9168-dc1d-4b7b-9ad1-d7df196cb4c7')),
        ),
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='236487127558267', editable=False, max_length=15),
        ),
    ]
