# Generated by Django 5.0.6 on 2024-07-10 10:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0021_members_uuid_alter_members_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='403329495459524', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('eeb97fca-fbb6-4e95-89ff-2286e2664f3e')),
        ),
    ]
