# Generated by Django 5.0.6 on 2024-07-10 10:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0022_alter_members_account_number_alter_members_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='826711401788064', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('3fa3cac4-2778-4c3e-b53d-8f8fb90cec94')),
        ),
    ]
