# Generated by Django 5.0.6 on 2024-07-12 02:28

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0024_alter_members_account_number_alter_members_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='745450367912390', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a84677d7-26d5-4656-b702-b3910c01c46b')),
        ),
    ]
