# Generated by Django 5.0.6 on 2024-07-12 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0025_alter_members_account_number_alter_members_uuid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='members',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='members',
            name='email',
        ),
        migrations.RemoveField(
            model_name='members',
            name='name',
        ),
        migrations.RemoveField(
            model_name='members',
            name='password',
        ),
        migrations.RemoveField(
            model_name='members',
            name='uuid',
        ),
        migrations.AddField(
            model_name='members',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='uploads'),
        ),
        migrations.AddField(
            model_name='members',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
