# Generated by Django 5.0.6 on 2024-07-12 03:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0027_remove_members_picture_remove_members_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='247978923232139', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('b90c94f9-5360-4e11-a73f-4cab8e3c78da')),
        ),
    ]
