# Generated by Django 5.0.6 on 2024-07-12 03:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0028_alter_members_account_number_alter_members_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='504849108428186', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('6167adb1-0907-43b9-88a3-27bd835df412')),
        ),
    ]
