# Generated by Django 5.0.6 on 2024-07-12 03:46

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0029_alter_members_account_number_alter_members_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='098731120345666', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('ed0efa99-bdac-4207-9369-8fe5450f7abf')),
        ),
    ]
