# Generated by Django 5.0.6 on 2024-07-12 03:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0030_alter_members_account_number_alter_members_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='612077411752323', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('a7218f2f-cf61-4ea8-9872-2bdc9d001d84')),
        ),
    ]
