# Generated by Django 5.0.6 on 2024-07-12 03:57

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0032_alter_members_account_number_alter_members_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='account_number',
            field=models.CharField(default='309018897746558', editable=False, max_length=15),
        ),
        migrations.AlterField(
            model_name='members',
            name='uuid',
            field=models.UUIDField(default=uuid.UUID('f6cb8ac0-24c2-4b74-9f4c-a740041c4811')),
        ),
    ]
